### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by DanCardin** [stefanoborini/vai#161]
Doesn't work on windows.

First, it doesn't install curses. After manually doing so, it seems that your reliance on select.select([sys.stdin], [], []) in VScreen.py is windows Incompatible. After removing that line it runs fine, but expectedly doesn't get any input.

**Comment by stefanoborini** [comment]
My plan is already to ditch ncurses completely for other reasons, but this means I have to reimplement the terminal control myself.

For the select, it is indeed true. I am following more or less Qt on vaitk. The relevant code is in QEventLoop if I remember correctly, but I need to have different event loops and event handlers according to the platform. select works for linux and osx, but windows is a completely different beast.

I need more resources to do that.
