### ISSUE TITLE
Python error message purple box disappear when moving on same line

### ISSUE THREAD

**Issue by Jb00** [stefanoborini/vai#163]
Python error message purple box , example Invalid syntax, disappear if you move right or left on the same line.

**Comment by Jb00** [comment]
I like the few seconds popup, and having it configurable , where 0 = stay on the page.

**Comment by stefanoborini** [comment]
Good, I set it for 1.6. I also think it should behave that way.

**Comment by stefanoborini** [comment]
Trying to implement it for 1.5, as I can't release it before coming back from vacation, I may just get it through.

**Comment by stefanoborini** [comment]
For now it's not configurable (do we need it?) but it's fixed.
