### ISSUE TITLE
Try : else error

### ISSUE THREAD

**Issue by Jb00** [stefanoborini/vai#166]
I have this code (example) with a try ; else , which is valid code. 

37     |    .   # Figure out where we are 
 38    |    .   try: 
 39    |    .   .    self.qweqwe 
 40    |    .   except Exception: 
 41    |    .   .   pass 
 42  I |    .    else: 
 43    |    .   .    pass 

unindent does not match any outer indentation level

**Comment by stefanoborini** [comment]
Do you have more information on this bug? I am getting something from the backlog, as I can't release until I get home from vacation, so I still have 10 days available.

It's not critical, so we can postpone it to 1.6

**Comment by Jb00** [comment]
Hi,

Please junk it.  It was related to https://github.com/stefanoborini/vai/issues/165, where saving the file mid try statement, was showing a warning, then never going away.

Thanks,

**Comment by stefanoborini** [comment]
ok!
