### ISSUE TITLE
External color schemes infrastructure

### ISSUE THREAD

**Issue by stefanoborini** [stefanoborini/vai#42]
Currently, the SyntaxColor class provides only default color schema.
Refine the color schema, and introduce external files where to store color schemas. The user can then select the one of choice in the config file.

**Comment by szaghi** [comment]
The colorscheme is probably the first thing the end-user try to customized (I have just tried to do it...). I am not feel at home with a schema other than mine. I vote this feature.

Anyhow, great work!

**Comment by stefanoborini** [comment]
Done for syntax colors (which is what this feature is about). Coloring of the interface is a different matter and will come later.
